#!/usr/bin/env bash
#
# apply-readme.sh - Update README.md with _dockerlists_*.md content
#
# Usage: apply-readme.sh [OPTIONS]
#
# Options:
#   -h, --help      Show this help and exit
#   -v, --version   Show version information
#   -n, --dry-run   Show what would change without writing files
#

set -Eeuo pipefail

readonly MIN_BASH_VERSION=4
readonly SCRIPT_NAME="${BASH_SOURCE[0]##*/}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_DIR
readonly SCRIPT_VERSION="1.0.0"

# --- Logging (color codes disabled if not a terminal) ---
if [[ -t 2 ]]; then
  readonly C_RED='\033[0;31m'
  readonly C_YELLOW='\033[0;33m'
  readonly C_CYAN='\033[0;36m'
  readonly C_RESET='\033[0m'
else
  readonly C_RED='' C_YELLOW='' C_CYAN='' C_RESET=''
fi

log_info()  { printf '%b[INFO]%b %s\n' "$C_CYAN" "$C_RESET" "$*" >&2; }
log_warn()  { printf '%b[WARN]%b %s\n' "$C_YELLOW" "$C_RESET" "$*" >&2; }
log_error() { printf '%b[ERROR]%b %s\n' "$C_RED" "$C_RESET" "$*" >&2; }
die()       { log_error "$1"; exit "${2:-1}"; }

check_bash_version() {
  if [[ "${BASH_VERSINFO[0]}" -lt "$MIN_BASH_VERSION" ]]; then
    log_error "Bash $MIN_BASH_VERSION+ required. Found: $BASH_VERSION"
    if [[ "$OSTYPE" == darwin* ]]; then
      log_info "macOS detected. Install modern Bash via Homebrew: brew install bash"
    fi
    exit 1
  fi
}

usage() {
  cat <<EOF
Usage: $SCRIPT_NAME [OPTIONS]

Updates README.md by inserting the content of:
  - _dockerlists_debian.md
  - _dockerlists_alpine.md
  - _dockerlists_test.md

and updates the "## Versions (YYYY-MM-DD)" date.

Options:
  -h, --help      Show this help and exit
  -v, --version   Show version information
  -n, --dry-run   Show what would change without writing files
EOF
}

show_version() {
  echo "$SCRIPT_NAME version $SCRIPT_VERSION"
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Required command not found on PATH: $1"
}

mktemp_file() {
  local tmp
  if tmp="$(mktemp 2>/dev/null)"; then
    echo "$tmp"
    return 0
  fi
  mktemp -t "${SCRIPT_NAME%.sh}.XXXXXX"
}

main() {
  check_bash_version
  cd "$SCRIPT_DIR"

  local dry_run=false
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h|--help) usage; exit 0 ;;
      -v|--version) show_version; exit 0 ;;
      -n|--dry-run) dry_run=true; shift ;;
      -*) die "Unknown option: $1" 2 ;;
      *) die "Unexpected argument: $1" 2 ;;
    esac
  done

  require_cmd awk
  require_cmd date
  require_cmd mktemp
  require_cmd mv
  require_cmd wc

  local readme_file="README.md"
  local -a groups=(debian alpine test)
  local -a tmp_files=()
  cleanup() {
    local f
    for f in "${tmp_files[@]}"; do
      rm -f "$f"
    done
  }
  trap cleanup EXIT INT TERM

  local today
  today="$(date +%Y-%m-%d)"

  [[ -f "$readme_file" ]] || die "File not found: $readme_file"

  local group dockerlist_file
  for group in "${groups[@]}"; do
    dockerlist_file="_dockerlists_${group}.md"
    [[ -f "$dockerlist_file" ]] || die "Required file not found: $dockerlist_file"
  done

  log_info "Updating $readme_file (date: $today)"

  local tmp
  tmp="$(mktemp_file)"
  tmp_files+=("$tmp")

  awk -v today="$today" '
    {
      if ($0 ~ /^## Versions \([0-9]{4}-[0-9]{2}-[0-9]{2}\)$/) {
        sub(/\([0-9]{4}-[0-9]{2}-[0-9]{2}\)$/, "(" today ")")
      }
      print
    }
  ' "$readme_file" > "$tmp"

  if [[ "$dry_run" == "true" ]]; then
    log_info "[DRY RUN] Would update versions date in $readme_file"
  else
    mv "$tmp" "$readme_file"
    chmod 644 "$readme_file"
  fi

  for group in "${groups[@]}"; do
    dockerlist_file="_dockerlists_${group}.md"
    tmp="$(mktemp_file)"
    tmp_files+=("$tmp")

    log_info "Updating ${group} section from ${dockerlist_file}"
    awk -v group="$group" -v content_file="$dockerlist_file" '
      $0 ~ "<!-- " group "_autogenerated_begin  -->" {
        print
        while ((getline line < content_file) > 0) print line
        close(content_file)
        in_block = 1
        next
      }
      $0 ~ "<!-- " group "_autogenerated_end  -->" {
        in_block = 0
        print
        next
      }
      !in_block { print }
    ' "$readme_file" > "$tmp"

    if [[ "$dry_run" == "true" ]]; then
      log_info "[DRY RUN] Would update ${group} section in $readme_file"
    else
      mv "$tmp" "$readme_file"
      chmod 644 "$readme_file"
    fi
  done

  local readme_size_limit=25000
  local file_size
  file_size="$(wc -c < "$readme_file" | tr -d '[:space:]')"
  log_info "$readme_file size: ${file_size} bytes (Docker Hub limit: ${readme_size_limit})"
  if [[ "$file_size" -ge "$readme_size_limit" ]]; then
    log_warn "$readme_file is too large (${file_size} bytes); Docker Hub may truncate it."
  fi

  if [[ "$dry_run" == "true" ]]; then
    log_info "[DRY RUN] Completed"
  else
    log_info "[OK] $readme_file updated"
  fi
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
