#!/usr/bin/env bash
#
# update.sh - Generate Dockerfiles and matrix.yml for PostGIS Docker images
#
# Usage: update.sh [OPTIONS] [VERSION_DIR...]
#
# Derived from https://github.com/docker-library/postgres/blob/master/update.sh
# Minimal test to keep in sync: ./ci/test-update.sh
#

set -Eeuo pipefail

readonly MIN_BASH_VERSION=4
readonly SCRIPT_NAME="${BASH_SOURCE[0]##*/}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_DIR
readonly SCRIPT_VERSION="1.0.0"

# --- Logging (color codes disabled if not a terminal) ---
if [[ -t 2 ]]; then
    readonly C_RED='\033[0;31m'
    readonly C_YELLOW='\033[0;33m'
    readonly C_CYAN='\033[0;36m'
    readonly C_RESET='\033[0m'
else
    readonly C_RED='' C_YELLOW='' C_CYAN='' C_RESET=''
fi

log_info()  { printf '%b[INFO]%b %s\n' "$C_CYAN" "$C_RESET" "$*" >&2; }
log_warn()  { printf '%b[WARN]%b %s\n' "$C_YELLOW" "$C_RESET" "$*" >&2; }
log_error() { printf '%b[ERROR]%b %s\n' "$C_RED" "$C_RESET" "$*" >&2; }
die()       { log_error "$1"; exit "${2:-1}"; }

log_section() {
    local title="$1"
    log_info "===== ${title} ====="
}

log_variant_line() {
    local level="$1"  # info|warn|error
    local target="$2"
    local variant="$3"
    local text="$4"

    local prefix="${target} ${variant}"
    case "$level" in
        info)  log_info "${prefix} | ${text}" ;;
        warn)  log_warn "${prefix} | ${text}" ;;
        error) log_error "${prefix} | ${text}" ;;
        *)     log_info "${prefix} | ${text}" ;;
    esac
}

log_variant_cont() {
    local level="$1"  # info|warn|error
    local target="$2"
    local variant="$3"
    local text="$4"

    local prefix="${target} ${variant}"
    local pad
    pad="$(printf '%*s' "${#prefix}" '')"

    case "$level" in
        info)  log_info "${pad} | ${text}" ;;
        warn)  log_warn "${pad} | ${text}" ;;
        error) log_error "${pad} | ${text}" ;;
        *)     log_info "${pad} | ${text}" ;;
    esac
}

log_variant_tags_output() {
    local level="$1"  # info|warn|error
    local target="$2"
    local variant="$3"
    local tags="${4:-}"
    local output="${5:-}"

    if [[ -n "$tags" ]]; then
        log_variant_cont "$level" "$target" "$variant" "tags=\"${tags}\""
    else
        log_variant_cont "$level" "$target" "$variant" "tags=\"(none)\""
    fi
    log_variant_cont "$level" "$target" "$variant" "output=\"${output}\""
}

# --- Platform Check ---
check_bash_version() {
    if [[ "${BASH_VERSINFO[0]}" -lt "$MIN_BASH_VERSION" ]]; then
        log_error "Bash $MIN_BASH_VERSION+ required. Found: $BASH_VERSION"
        if [[ "$OSTYPE" == darwin* ]]; then
            log_info "macOS detected. Install modern Bash via: brew install bash"
        fi
        exit 1
    fi
}

# --- Usage ---
usage() {
    cat <<EOF
Usage: $SCRIPT_NAME [OPTIONS] [VERSION_DIR...]

Generate Dockerfiles and matrix.yml for PostGIS Docker images.

Arguments:
    VERSION_DIR     Specific version directory to process (e.g., 17-3.5).
                    If specified, only generates Dockerfiles for that version
                    without updating global metadata (README.md, matrix.yml).
                    If not specified, processes all versions and updates all files.

Options:
    -h, --help      Show this help message and exit
    -v, --version   Show version information

Examples:
    $SCRIPT_NAME              # Process all versions, update README.md and matrix.yml
    $SCRIPT_NAME 17-3.5       # Process only 17-3.5, skip global updates
    $SCRIPT_NAME 17-3.5 18-3.6
EOF
}

show_version() {
    echo "$SCRIPT_NAME version $SCRIPT_VERSION"
}

require_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "Required command not found on PATH: $1"
}

install_support_scripts() {
    local dest_dir="$1"
    cp -p initdb-postgis.sh update-postgis.sh "$dest_dir/"
}

cd "$SCRIPT_DIR"

readonly AUTOGENERATED_NOTICE='NOTE: THIS DOCKERFILE IS GENERATED VIA "./update.sh"! PLEASE DO NOT EDIT IT DIRECTLY.'
readonly DOCKERHUB_TAGS_URL_BASE="https://registry.hub.docker.com/r/postgis/postgis/tags?page=1&name="
readonly GITHUB_REPO_BLOB_BASE="https://github.com/postgis/docker-postgis/blob/master"

# Matrix configuration for CI/CD
readonly MATRIX_FILE="matrix.yml"

# The following version is considered to be the 'latest' or 'alpine'.
# Not readonly: CI/unit tests temporarily override it (see ci/test-update.sh).
LATEST_VERSION=17-3.5

readonly DEFAULT_ALPINE_SUITE='3.22'
readonly DEFAULT_DEBIAN_SUITE='bullseye-slim'
declare -Ar DEBIAN_SUITE=(
    # https://github.com/docker-library/postgres/issues/582
    [13]='bullseye-slim'
    [14]='bullseye-slim'
    [15]='bullseye-slim'
    [16]='bullseye-slim'
    [17]='bullseye-slim'
    [18]='trixie-slim'
    [19]='trixie-slim'
)

readonly PACKAGES_BASE='http://apt.postgresql.org/pub/repos/apt/dists/'
declare -ar OPTIMIZED_BUCKETS=(debian alpine test)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

get_postgis_deb_suffix() {
    local majmin="$1"
    local major="${majmin%%.*}"

    if [[ ! "$major" =~ ^[0-9]+$ ]]; then
        die "Invalid PostGIS major.minor version: $majmin"
    fi

    echo "$major"
}

render_template() {
    local template="$1"
    local out="$2"
    shift 2

    local -a sed_args=()
    local kv key val
    for kv in "$@"; do
        key="${kv%%=*}"
        val="${kv#*=}"
        val="${val//\\/\\\\}"
        val="${val//&/\\&}"
        val="${val//|/\\|}"
        sed_args+=("-e" "s|${key}|${val}|g")
    done

    sed "${sed_args[@]}" "$template" > "$out"
}

detect_optimized_bucket() {
    local version_dir="$1"
    local variant="${2:-default}"

    if [[ "$version_dir" =~ alpha|beta|rc|master ]]; then
        echo "test"
    elif [[ "$variant" == "alpine" ]]; then
        echo "alpine"
    else
        echo "debian"
    fi
}

# Build Docker tag list for matrix.yml
build_tags() {
    local pg="$1"
    local postgis="$2"
    local variant="$3"
    local os_label="$4"
    local patch="$5"
    local combo="${pg}-${postgis}"
    local -a tags=()
    local stable_patch_re='^[0-9]+\.[0-9]+\.[0-9]+$'
    local prerelease_patch_re='^[0-9]+\.[0-9]+\.[0-9]+(alpha|beta|rc)[0-9]+$'

    if [[ "$variant" == "alpine" ]]; then
        tags+=("${combo}-alpine")
        tags+=("${combo}-${os_label}")
    else
        tags+=("${combo}")
        tags+=("${combo}-${os_label}")
    fi

    # Add patch tag for stable and pre-release versions (alpha/beta/rc).
    if [[ "$patch" =~ $stable_patch_re || "$patch" =~ $prerelease_patch_re ]]; then
        tags+=("${pg}-${patch}-${os_label}")
    fi

    # 'latest' and 'alpine' tags are reserved for stable releases only.
    if [[ "$combo" == "$LATEST_VERSION" && "$patch" =~ $stable_patch_re ]]; then
        if [[ "$variant" == "default" ]]; then
            tags+=("latest")
        elif [[ "$variant" == "alpine" ]]; then
            tags+=("alpine")
        fi
    fi

    echo "${tags[*]}"
}

# Correct version sorting
version_reverse_sort() {
    sed -r "s/([0-9]+\.[0-9]+\.[0-9]+$)/\1\.9991/" | sort -Vr | sed s/\.9991$//
}

fetch_postgis_versions() {
    local REPO="postgis/postgis"
    local PER_PAGE=100
    local page=1
    postgis_all_v3_versions=""

    while true; do
        local response
        response="$(curl --fail --show-error --silent "https://api.github.com/repos/$REPO/tags?per_page=$PER_PAGE&page=$page")" || {
            log_warn "Failed to fetch postgis tags from api.github.com"
            return 1
        }

        if echo "$response" | grep -q "API rate limit exceeded"; then
            die "API rate limit exceeded: $response"
        fi

        local tags count
        tags=$(echo "$response" | jq -r '.[].name' 2>/dev/null || true)
        count=$(echo "$tags" | sed '/^$/d' | wc -l)
        if ((count == 0)); then
            break
        fi

        if ((page > 12)); then
            die "Too many pages (${page}) while fetching PostGIS tags"
        fi

        postgis_all_v3_versions+=" $tags"
        ((page++))
    done
}

# ---------------------------------------------------------------------------
# Version resolution and recording
# ---------------------------------------------------------------------------

# Outputs (globals):
#   postgisMajMin, postgisPackageName, postgisFullVersion, postgisMajor, postgisDocSrc
resolve_debian_postgis_version() {
    local postgres_main="$1"
    local postgis_version="$2"
    local version_list="$3"
    local version_dir="$4"
    local suite="$5"

    postgisPackageName=""
    postgisFullVersion=""
    postgisMajor=""
    postgisDocSrc=""
    postgisMajMin=""

    debian_resolve_requested=""
    debian_resolve_found=""
    debian_resolve_found_ver=""
    debian_resolve_reason=""
    debian_resolve_status="OK"

    if [[ "$postgis_version" == "master" ]]; then
        postgisFullVersion="$postgis_version"
        postgisDocSrc="development: postgis, geos, proj, gdal"
        debian_resolve_status="OK"
        return 0
    fi

    postgisMajMin="$( echo "${postgis_version}" | cut -d. -f1 ).$( echo "${postgis_version}" | cut -d. -f2 )"
    debian_resolve_requested="$postgisMajMin"

    postgisPackageName="postgresql-${postgres_main}-postgis-$(get_postgis_deb_suffix "$postgisMajMin")"
    debian_resolve_found_ver="$(echo "$version_list" | awk -F ': ' '$1 == "Package" { pkg = $2 } $1 == "Version" && pkg == "'"$postgisPackageName"'" { print $2; exit }' || true)"
    postgisFullVersion="$debian_resolve_found_ver"

    if [[ -z "$postgisFullVersion" ]]; then
        debian_resolve_status="SKIP"
        debian_resolve_reason="Debian package not available"
        return 0
    fi

    local debianPostgisMajMin
    debianPostgisMajMin="$( echo "${postgisFullVersion}" | cut -d. -f1 ).$( echo "${postgisFullVersion}" | cut -d. -f2 )"
    debian_resolve_found="$debianPostgisMajMin"
    if [[ "$debianPostgisMajMin" == "$postgisMajMin" ]]; then
        postgisMajor="$(get_postgis_deb_suffix "$postgisMajMin")"
        postgisDocSrc="${postgisFullVersion%%+*}"
    else
        debian_resolve_status="SKIP"
        debian_resolve_reason="PostGIS major.minor mismatch"
        postgisFullVersion=""
        postgisMajor=""
        postgisDocSrc=""
    fi
}

# Select the PostGIS source version for Alpine builds.
# - Prefer the latest stable version (no alpha/beta/rc) for the same major.minor series.
# - If none exists, fall back to the requested pre-release (if requested is alpha/beta/rc),
#   otherwise fall back to the latest available tag for the series (including pre-releases).
select_postgis_src_version_for_alpine() {
    local majmin="$1"          # e.g. 3.6
    local requested="$2"       # e.g. 3.6 (from directory) or 3.6.0beta1
    local versions_string="$3" # space-separated list of tags

    local major minor stable
    major="${majmin%%.*}"
    minor="${majmin#*.}"

    stable="$(
        tr ' ' '\n' <<< "$versions_string" \
            | grep "^${major}\\.${minor}\\." \
            | grep -v '[a-zA-Z]' \
            | head -n 1 \
            || true
    )"
    if [[ -n "$stable" ]]; then
        echo "$stable"
        return 0
    fi

    if [[ "$requested" =~ alpha|beta|rc ]]; then
        echo "$requested"
    else
        tr ' ' '\n' <<< "$versions_string" \
            | grep "^${major}\\.${minor}\\." \
            | head -n 1 \
            || true
    fi
}

# Outputs (globals):
#   srcVersion, srcSha256, postgisDocSrc (updated for Alpine docs/tags)
resolve_alpine_postgis_version() {
    local version_dir="$1"
    local postgis_version="$2"

    srcVersion=""
    srcSha256=""

    if [[ "$postgis_version" == "master" ]]; then
        return 0
    fi

    if [[ -d "$version_dir/alpine" ]]; then
        srcVersion="$(select_postgis_src_version_for_alpine "$postgisMajMin" "$postgis_version" "$postgis_all_v3_versions_array_string")"
        if [[ -z "$srcVersion" ]]; then
            die "Unable to resolve PostGIS source version for alpine (postgisMajMin=$postgisMajMin, requested=$postgis_version)"
        fi
    else
        srcVersion="${postgisFullVersion%%+*}"
    fi

    if [[ -n "${postgis_tarball_sha256_cache[$srcVersion]:-}" ]]; then
        srcSha256="${postgis_tarball_sha256_cache[$srcVersion]}"
    else
        local tarball_url="https://github.com/postgis/postgis/archive/$srcVersion.tar.gz"
        if ! srcSha256="$(curl -fsSL "$tarball_url" | sha256sum | awk '{ print $1 }')"; then
            die "Failed to download PostGIS tarball: $tarball_url"
        fi
        postgis_tarball_sha256_cache["$srcVersion"]="$srcSha256"
    fi
    postgisDocSrc="$srcVersion"
}

record_target() {
    local version_dir="$1"
    local postgres_display="$2"
    local postgres_main="$3"
    local postgis_version="$4"
    local variant="$5"      # default|alpine
    local os_doc="$6"       # e.g. debian:bullseye
    local os_label="$7"     # e.g. bullseye or alpine3.22
    local doc_src="$8"      # PostGIS column + patch for tag gen

    local bucket image_tag dockerfile_path
    if [[ "$variant" == "alpine" ]]; then
        bucket="$(detect_optimized_bucket "$version_dir" "alpine")"
        image_tag="${version_dir}-alpine"
        dockerfile_path="${version_dir}/alpine/Dockerfile"
    else
        bucket="$(detect_optimized_bucket "$version_dir" "default")"
        image_tag="${version_dir}"
        dockerfile_path="${version_dir}/Dockerfile"
        variant="default"
    fi

    echo "| [postgis/postgis:${image_tag}](${DOCKERHUB_TAGS_URL_BASE}${image_tag}) | [Dockerfile](${GITHUB_REPO_BLOB_BASE}/${dockerfile_path}) | ${os_doc} | ${postgres_display} | ${doc_src} |" >> "_dockerlists_${bucket}.md"

    local tags
    tags="$(build_tags "${postgres_main}" "${postgis_version}" "${variant}" "${os_label}" "${doc_src}")"
    echo "  - { postgres: '${postgres_main}', postgis: '${postgis_version}', variant: '${variant}', tags: '${tags}' }" >> "_matrixlist_${bucket}.yml"
    echo "$tags"
}

# ---------------------------------------------------------------------------
# Generation phases
# ---------------------------------------------------------------------------

init_outputs() {
    for optimized in "${OPTIMIZED_BUCKETS[@]}"; do
        rm -f "_dockerlists_${optimized}.md"
        {
            echo "<!-- This part is automatically generated by ./update.sh. Do not modify this section manually. -->"
            echo "| DockerHub image | Dockerfile | OS | Postgres | PostGIS |"
            echo "| --------------- | ---------- | -- | -------- | ------- |"
        } > "_dockerlists_${optimized}.md"

        rm -f "_matrixlist_${optimized}.yml"
        {
            echo "# This file is automatically generated by ./update.sh"
            echo "# Category: ${optimized}"
            echo "# Entries that successfully generated Dockerfiles"
            echo ""
        } > "_matrixlist_${optimized}.yml"
    done
}

fetch_git_hash() {
    local url="$1"
    local ref="$2"
    local name="$3"
    local hash

    if ! hash="$(git ls-remote "$url" "$ref" 2>/dev/null | awk '{ print $1; exit }')"; then
        log_warn "Failed to fetch $name git hash from $url"
        echo ""
        return 0
    fi

    if [[ -z "$hash" ]]; then
        log_warn "Empty $name git hash (ref: $ref) from $url"
        echo ""
        return 0
    fi

    # Validate git hash format: 40 chars (SHA-1) or 64 chars (SHA-256), hex only
    if [[ ! "$hash" =~ ^[0-9a-fA-F]{40}$ && ! "$hash" =~ ^[0-9a-fA-F]{64}$ ]]; then
        log_warn "Invalid $name git hash format: $hash"
        echo ""
        return 0
    fi

    log_info "$name git hash: ${hash:0:12}..."
    echo "$hash"
}

fetch_remote_state() {
    log_info "Fetching remote git hashes..."
    local -a repos=(
        "cgalGitHash|https://github.com/CGAL/cgal.git|heads/main|CGAL"
        "sfcgalGitHash|https://gitlab.com/SFCGAL/SFCGAL.git|heads/master|SFCGAL"
        "projGitHash|https://github.com/OSGeo/PROJ.git|heads/master|PROJ"
        "gdalGitHash|https://github.com/OSGeo/gdal.git|refs/heads/master|GDAL"
        "geosGitHash|https://github.com/libgeos/geos.git|heads/main|GEOS"
        "postgisGitHash|https://github.com/postgis/postgis.git|heads/master|PostGIS"
    )
    local entry var url ref name hash
    for entry in "${repos[@]}"; do
        IFS='|' read -r var url ref name <<< "$entry"
        hash="$(fetch_git_hash "$url" "$ref" "$name")"
        printf -v "$var" '%s' "$hash"
    done

    fetch_postgis_versions || die "Error fetching PostGIS versions"
    postgis_all_v3_versions="$(echo "$postgis_all_v3_versions" | sed '/^$/d' | grep '^3\.' | version_reverse_sort)"
    postgis_all_v3_versions_array_string="$(echo "$postgis_all_v3_versions" | tr '\n' ' ')"
    log_info "postgis_all_v3_versions_array_string = ${postgis_all_v3_versions_array_string}"
}

declare -a matrix_skip_comments=()
declare -A suitePackageList=()

# Populated in fetch_remote_state().
cgalGitHash=""
sfcgalGitHash=""
projGitHash=""
gdalGitHash=""
geosGitHash=""
postgisGitHash=""

# Mutable in-process cache to avoid re-downloading the same PostGIS tarball
# multiple times when several targets resolve to the same PostGIS source tag.
declare -A postgis_tarball_sha256_cache=()

generate_debian() {
    local version_dir="$1"
    local postgresVersion="$2"
    local postgres_main="$3"
    local postgis_version="$4"
    local suite="$5"
    local boostVersion="$6"

    if [[ -z "$postgisFullVersion" ]]; then
        echo " # placeholder Dockerfile"                                          > "$version_dir/Dockerfile"
        echo " # Debian version of postgis $postgisFullVersion is not detected!" >> "$version_dir/Dockerfile"
        echo " # This is an autogenerated message of ./update.sh "               >> "$version_dir/Dockerfile"
        rm -f "$version_dir/"*.sh "$version_dir/"*.md
        matrix_skip_comments+=("postgres: ${postgres_main}, postgis: ${postgis_version}, variant: default - Reason: placeholder (Debian ${suite} package not available)")

        local _postgisMinor
        _postgisMinor="$(echo "$postgisMajMin" | cut -d. -f2)"
        postgisFullVersion="$(echo "$postgis_all_v3_versions" | grep "^3\.${_postgisMinor}\." | grep -v '[a-zA-Z]' | version_reverse_sort | head -n 1 || true)"
        if [[ -z "${postgisFullVersion}" ]]; then
            postgisFullVersion="$(echo "$postgis_all_v3_versions" | grep "^3\.${_postgisMinor}\." | version_reverse_sort | head -n 1 || true)"
        fi
        postgisDocSrc="$postgisFullVersion"
        return 0
    fi

    install_support_scripts "$version_dir/"

    local template
    if [[ "$postgis_version" == "master" ]]; then
        template="Dockerfile.master.template"
    else
        template="Dockerfile.template"
    fi

    render_template "$template" "$version_dir/Dockerfile" \
        "%%TXT_AUTOGENERATED%%=$AUTOGENERATED_NOTICE" \
        "%%PG_MAJOR%%=$postgresVersion" \
        "%%POSTGIS_MAJOR%%=$postgisMajor" \
        "%%POSTGIS_VERSION%%=$postgisFullVersion" \
        "%%POSTGIS_GIT_HASH%%=$postgisGitHash" \
        "%%CGAL_GIT_HASH%%=$cgalGitHash" \
        "%%SFCGAL_GIT_HASH%%=$sfcgalGitHash" \
        "%%PROJ_GIT_HASH%%=$projGitHash" \
        "%%GDAL_GIT_HASH%%=$gdalGitHash" \
        "%%GEOS_GIT_HASH%%=$geosGitHash" \
        "%%BOOST_VERSION%%=$boostVersion" \
        "%%DEBIAN_VERSION%%=$suite"

    local tags
    tags="$(record_target "$version_dir" "$postgresVersion" "$postgres_main" "$postgis_version" "default" "debian:${suite}" "${suite}" "$postgisDocSrc")"
    echo "$tags"
}

generate_alpine() {
    local version_dir="$1"
    local postgresVersion="$2"
    local postgres_main="$3"
    local postgis_version="$4"

    local variant="alpine"
    if [[ ! -d "$version_dir/$variant" ]]; then
        return 0
    fi

    install_support_scripts "$version_dir/$variant/"

    render_template "Dockerfile.alpine.template" "$version_dir/$variant/Dockerfile" \
        "%%TXT_AUTOGENERATED%%=$AUTOGENERATED_NOTICE" \
        "%%PG_MAJOR%%=$postgresVersion" \
        "%%POSTGIS_VERSION%%=$srcVersion" \
        "%%POSTGIS_SHA256%%=$srcSha256"

    local tags
    tags="$(record_target "$version_dir" "$postgresVersion" "$postgres_main" "$postgis_version" "alpine" "alpine:${DEFAULT_ALPINE_SUITE}" "alpine${DEFAULT_ALPINE_SUITE}" "$postgisDocSrc")"
    echo "$tags"
}

process_version() {
    local version_dir="$1"
    local postgresVersion postgisVersion
    IFS=- read -r postgresVersion postgisVersion <<< "$version_dir"

    log_section "Generate ${version_dir}"

    local tag suite
    tag="${DEBIAN_SUITE[$postgresVersion]:-$DEFAULT_DEBIAN_SUITE}"
    suite="${tag%%-slim}"

    if [ -z "${suitePackageList["$suite"]:+isset}" ]; then
        suitePackageList["$suite"]="$(curl -fsSL "${PACKAGES_BASE}/${suite}-pgdg/main/binary-amd64/Packages.bz2" | bunzip2)"
    fi

    local postgresVersionMain versionList
    postgresVersionMain="$(echo "$postgresVersion" | awk -F 'alpha|beta|rc' '{print $1}')"
    versionList="$(echo "${suitePackageList["$suite"]}"; curl -fsSL "${PACKAGES_BASE}/${suite}-pgdg/${postgresVersionMain}/binary-amd64/Packages.bz2" | bunzip2)"

    local boostVersion
    case "$suite" in
        bullseye) boostVersion="1.74.0" ;;
        trixie)   boostVersion="1.88.0" ;;
        *) die "Unknown debian suite: ${suite}" ;;
    esac

    resolve_debian_postgis_version "$postgresVersionMain" "$postgisVersion" "$versionList" "$version_dir" "$suite"

    local debian_tags=""
    local debian_prefix_target="$version_dir"
    local debian_prefix_variant="debian"
    local debian_output="./${version_dir}/Dockerfile"

    if [[ "$postgisVersion" == "master" ]]; then
        debian_tags="$(generate_debian "$version_dir" "$postgresVersion" "$postgresVersionMain" "$postgisVersion" "$suite" "$boostVersion" || true)"
        log_variant_line info "$debian_prefix_target" "$debian_prefix_variant" "status=OK suite=${tag} postgis=master source=git"
        log_variant_tags_output info "$debian_prefix_target" "$debian_prefix_variant" "$debian_tags" "$debian_output"
    elif [[ "${debian_resolve_status}" == "SKIP" ]]; then
        generate_debian "$version_dir" "$postgresVersion" "$postgresVersionMain" "$postgisVersion" "$suite" "$boostVersion" >/dev/null || true
        log_variant_line warn "$debian_prefix_target" "$debian_prefix_variant" "status=SKIP suite=${tag} pkg=${postgisPackageName}"

        if [[ "${debian_resolve_reason}" == "PostGIS major.minor mismatch" ]]; then
            log_variant_cont warn "$debian_prefix_target" "$debian_prefix_variant" "reason=\"${debian_resolve_reason}\" requested=${debian_resolve_requested} found=${debian_resolve_found} found_ver=${debian_resolve_found_ver}"
        else
            log_variant_cont warn "$debian_prefix_target" "$debian_prefix_variant" "reason=\"${debian_resolve_reason}\" requested=${debian_resolve_requested}"
        fi

        log_variant_tags_output warn "$debian_prefix_target" "$debian_prefix_variant" "" "(skipped)"
    else
        debian_tags="$(generate_debian "$version_dir" "$postgresVersion" "$postgresVersionMain" "$postgisVersion" "$suite" "$boostVersion" || true)"
        log_variant_line info "$debian_prefix_target" "$debian_prefix_variant" "status=OK pkg=${postgisPackageName} ver=${postgisFullVersion} suite=${tag}"
        log_variant_tags_output info "$debian_prefix_target" "$debian_prefix_variant" "$debian_tags" "$debian_output"
    fi

    if [[ -d "$version_dir/alpine" ]]; then
        resolve_alpine_postgis_version "$version_dir" "$postgisVersion"
        local alpine_tags=""
        local alpine_prefix_variant="alpine"
        local alpine_output="./${version_dir}/alpine/Dockerfile"
        local alpine_suite="alpine${DEFAULT_ALPINE_SUITE}"

        alpine_tags="$(generate_alpine "$version_dir" "$postgresVersion" "$postgresVersionMain" "$postgisVersion" || true)"
        log_variant_line info "$version_dir" "$alpine_prefix_variant" "status=OK selected=${srcVersion} suite=${alpine_suite}"
        log_variant_tags_output info "$version_dir" "$alpine_prefix_variant" "$alpine_tags" "$alpine_output"
    fi
}

generate_matrix_yml() {
    local output_file="$1"
    local temp_file
    temp_file="$(mktemp)" || die "Failed to create temporary file"
    trap 'rm -f "$temp_file"' RETURN

    cat > "$temp_file" << EOF
# =============================================================================
# WARNING: AUTOMATICALLY GENERATED by ./update.sh - DO NOT EDIT MANUALLY!
# Used by: .github/workflows/*.yml
# =============================================================================
# - build_targets: All buildable postgres-postgis-variant combinations
# =============================================================================

EOF

    if [ ${#matrix_skip_comments[@]} -gt 0 ]; then
        echo "# --- Placeholder/skipped combinations (NOT included in build target list) ---" >> "$temp_file"
        for comment in "${matrix_skip_comments[@]}"; do
            echo "# - ${comment}" >> "$temp_file"
        done
        echo "" >> "$temp_file"
    fi

    echo "build_targets:" >> "$temp_file"

    local has_entries=false
    for optimized in "${OPTIMIZED_BUCKETS[@]}"; do
        if [ -f "_matrixlist_${optimized}.yml" ]; then
            grep "^  -" "_matrixlist_${optimized}.yml" >> "$temp_file" 2>/dev/null && has_entries=true
        fi
    done

    if [ "$has_entries" = false ]; then
        echo "  []" >> "$temp_file"
    fi

    local target_count
    target_count=$(grep -c "^  - { postgres:" "$temp_file" || echo "0")
    {
        echo ""
        echo ""
        echo "# =============================================================================="
        echo "# Summary: ${target_count} combinations"
        echo "# =============================================================================="
        echo "# End of matrix.yml"
    } >> "$temp_file"

    if [ -f "$output_file" ] && cmp -s "$temp_file" "$output_file"; then
        log_info "matrix.yml unchanged"
        rm -f "$temp_file"
    else
        mv "$temp_file" "$output_file"
        log_info "matrix.yml generated/updated"
    fi
    trap - RETURN
}

main() {
    check_bash_version

    # Parse options
    local -a args=()
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h|--help)
                usage
                exit 0
                ;;
            -v|--version)
                show_version
                exit 0
                ;;
            --)
                shift
                args+=("$@")
                break
                ;;
            -*)
                die "Unknown option: $1. Use --help for usage information." 2
                ;;
            *)
                args+=("$1")
                shift
                ;;
        esac
    done

    # Check required dependencies
    local -a deps=(curl jq git bunzip2 sha256sum)
    local dep
    for dep in "${deps[@]}"; do
        require_cmd "$dep"
    done

    local versions=( "${args[@]}" )
    local update_all=false

    if [ ${#versions[@]} -eq 0 ]; then
        update_all=true
        shopt -s nullglob
        versions=( */Dockerfile )
        shopt -u nullglob
    fi
    versions=( "${versions[@]%/Dockerfile}" )

    mapfile -t versions < <(printf '%s\n' "${versions[@]}" | sort -V)

    if [[ "$update_all" == true ]]; then
        init_outputs
    else
        log_info "Specific version(s) requested: ${versions[*]}"
        log_info "Skipping global metadata updates (README.md, matrix.yml)"
    fi

    fetch_remote_state

    for version_dir in "${versions[@]}"; do
        process_version "$version_dir"
    done

    if [[ "$update_all" == true ]]; then
        log_info "|-------------------------------|"
        log_info "|-   Generated README tables   -|"
        log_info "|-------------------------------|"
        for optimized in "${OPTIMIZED_BUCKETS[@]}"; do
            log_info "---- ${optimized} [ _dockerlists_${optimized}.md ] ----"
            cat "_dockerlists_${optimized}.md"
            echo " "
        done

        log_info "Applying README updates"
        bash ./apply-readme.sh

        log_info "Generating matrix.yml from _matrixlist_*.yml files"
        generate_matrix_yml "$MATRIX_FILE"
    fi

    log_info "update done && git status:"
    git status
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    main "$@"
fi
