#!/usr/bin/env bash
#
# update.sh - Generate Dockerfiles and matrix.yml for PostGIS Docker images
#
# Usage: update.sh [OPTIONS] [VERSION_DIR...]
#
# Derived from https://github.com/docker-library/postgres/blob/master/update.sh
# Minimal test to keep in sync: ./ci/test-update.sh
#

set -Eeuo pipefail

readonly MIN_BASH_VERSION=4
readonly SCRIPT_NAME="${BASH_SOURCE[0]##*/}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_DIR

# --- Logging (color codes disabled if not a terminal) ---
if [[ -t 2 ]]; then
    readonly C_RED='\033[0;31m'
    readonly C_YELLOW='\033[0;33m'
    readonly C_CYAN='\033[0;36m'
    readonly C_RESET='\033[0m'
else
    readonly C_RED='' C_YELLOW='' C_CYAN='' C_RESET=''
fi

log_info()  { printf '%b[INFO]%b %s\n' "$C_CYAN" "$C_RESET" "$*" >&2; }
log_warn()  { printf '%b[WARN]%b %s\n' "$C_YELLOW" "$C_RESET" "$*" >&2; }
log_error() { printf '%b[ERROR]%b %s\n' "$C_RED" "$C_RESET" "$*" >&2; }
die()       { log_error "$1"; exit "${2:-1}"; }

# --- Platform Check ---
check_bash_version() {
    if [[ "${BASH_VERSINFO[0]}" -lt "$MIN_BASH_VERSION" ]]; then
        log_error "Bash $MIN_BASH_VERSION+ required. Found: $BASH_VERSION"
        if [[ "$OSTYPE" == darwin* ]]; then
            log_info "macOS detected. Install modern Bash via: brew install bash"
        fi
        exit 1
    fi
}

# --- Usage ---
usage() {
    cat <<EOF
Usage: $SCRIPT_NAME [OPTIONS] [VERSION_DIR...]

Generate Dockerfiles and matrix.yml for PostGIS Docker images.

Arguments:
    VERSION_DIR     Specific version directory to process (e.g., 17-3.5).
                    If specified, only generates Dockerfiles for that version
                    without updating global metadata (README.md, matrix.yml).
                    If not specified, processes all versions and updates all files.

Options:
    -h, --help      Show this help message and exit

Examples:
    $SCRIPT_NAME              # Process all versions, update README.md and matrix.yml
    $SCRIPT_NAME 17-3.5       # Process only 17-3.5, skip global updates
    $SCRIPT_NAME 17-3.5 18-3.6
EOF
}

require_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "Required command not found on PATH: $1"
}

cd "$SCRIPT_DIR"

readonly AUTOGENERATED_NOTICE='NOTE: THIS DOCKERFILE IS GENERATED VIA "./update.sh"! PLEASE DO NOT EDIT IT DIRECTLY.'
readonly DOCKERHUB_TAGS_URL_BASE="https://registry.hub.docker.com/r/postgis/postgis/tags?page=1&name="
readonly GITHUB_REPO_BLOB_BASE="https://github.com/postgis/docker-postgis/blob/master"

# Matrix configuration for CI/CD
readonly MATRIX_FILE="matrix.yml"

# Version pattern constants for tag classification
# Stable releases: pure semver like 3.4.0, 3.5.1
readonly STABLE_VERSION_PATTERN='^[0-9]+\.[0-9]+\.[0-9]+$'
# Pre-releases: semver with alpha/beta/rc suffix like 3.6.0alpha1, 3.6.0beta2, 3.6.0rc1
readonly PRERELEASE_VERSION_PATTERN='^[0-9]+\.[0-9]+\.[0-9]+(alpha|beta|rc)[0-9]+$'
# Directory names indicating test/development builds
readonly TEST_BUILD_PATTERN='alpha|beta|rc|master'

# Safety limit for GitHub API pagination.
# PostGIS has ~1000 tags, at 100 tags/page we expect ~10 pages max.
# Set to 12 to allow some headroom while preventing infinite loops.
readonly MAX_GITHUB_API_PAGES=12

# The following version is considered to be the 'latest' or 'alpine'.
# Not readonly: CI/unit tests temporarily override it (see ci/test-update.sh).
LATEST_VERSION=17-3.5

readonly DEFAULT_ALPINE_SUITE='3.22'
readonly DEFAULT_DEBIAN_SUITE='bullseye-slim'
# Pin PostgreSQL versions to specific Debian suites for package compatibility.
# This ensures we use Debian releases where the required PostGIS packages are available.
# See: https://github.com/docker-library/postgres/issues/582
declare -Ar DEBIAN_SUITE=(
    [13]='bullseye-slim'
    [14]='bullseye-slim'
    [15]='bullseye-slim'
    [16]='bullseye-slim'
    [17]='bullseye-slim'
    [18]='trixie-slim'
    [19]='trixie-slim'
)

readonly PACKAGES_BASE='http://apt.postgresql.org/pub/repos/apt/dists/'
declare -ar OPTIMIZED_BUCKETS=(debian alpine test)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Render a Dockerfile template by substituting placeholder variables.
#
# Arguments:
#   $1 - template_file: Path to template file
#   $2 - output_file: Path to output file
#   $@ - key=value pairs for substitution (e.g., "%%PG_MAJOR%%=17")
#
# Placeholders in the template use %%NAME%% format.
render_template() {
    local template_file="$1"
    local output_file="$2"
    shift 2

    local -a sed_args=()
    local key_value_pair placeholder_key replacement_value
    for key_value_pair in "$@"; do
        placeholder_key="${key_value_pair%%=*}"
        replacement_value="${key_value_pair#*=}"
        # Escape special sed characters in replacement value
        replacement_value="${replacement_value//\\/\\\\}"
        replacement_value="${replacement_value//&/\\&}"
        replacement_value="${replacement_value//|/\\|}"
        sed_args+=("-e" "s|${placeholder_key}|${replacement_value}|g")
    done

    sed "${sed_args[@]}" "$template_file" > "$output_file"
}

# Determine which CI bucket (debian/alpine/test) a build target belongs to.
# Test bucket is used for pre-release and development builds.
detect_optimized_bucket() {
    local version_dir="$1"
    local variant="${2:-default}"

    if [[ "$version_dir" =~ $TEST_BUILD_PATTERN ]]; then
        echo "test"
    elif [[ "$variant" == "alpine" ]]; then
        echo "alpine"
    else
        echo "debian"
    fi
}

# Build Docker tag list for matrix.yml
#
# Arguments:
#   $1 - postgres_version: PostgreSQL major version (e.g., "17")
#   $2 - postgis_version: PostGIS version (e.g., "3.5")
#   $3 - variant: "default" (Debian) or "alpine"
#   $4 - os_label: OS identifier for tags (e.g., "bullseye", "alpine3.22")
#   $5 - patch_version: Full PostGIS patch version (e.g., "3.5.0", "3.6.0beta1")
#
# Output: Space-separated list of Docker tags
build_tags() {
    local postgres_version="$1"
    local postgis_version="$2"
    local variant="$3"
    local os_label="$4"
    local patch_version="$5"
    local version_combo="${postgres_version}-${postgis_version}"
    local -a tags=()

    if [[ "$variant" == "alpine" ]]; then
        tags+=("${version_combo}-alpine")
        tags+=("${version_combo}-${os_label}")
    else
        tags+=("${version_combo}")
        tags+=("${version_combo}-${os_label}")
    fi

    # Add patch-level tag for stable and pre-release versions (alpha/beta/rc).
    # This allows users to pin to specific patch versions.
    if [[ "$patch_version" =~ $STABLE_VERSION_PATTERN || "$patch_version" =~ $PRERELEASE_VERSION_PATTERN ]]; then
        tags+=("${postgres_version}-${patch_version}-${os_label}")
    fi

    # 'latest' and 'alpine' convenience tags are reserved for stable releases only.
    # Pre-releases should never be tagged as 'latest' to avoid surprising users.
    if [[ "$version_combo" == "$LATEST_VERSION" && "$patch_version" =~ $STABLE_VERSION_PATTERN ]]; then
        if [[ "$variant" == "default" ]]; then
            tags+=("latest")
        elif [[ "$variant" == "alpine" ]]; then
            tags+=("alpine")
        fi
    fi

    echo "${tags[*]}"
}

# Sort version strings in reverse order, with stable releases before pre-releases.
#
# Problem: Standard version sort (sort -V) places "3.5.0" before "3.5.0beta1"
# because it sorts character-by-character. We want stable releases (3.5.0)
# to appear BEFORE pre-releases (3.5.0alpha1, 3.5.0beta1, 3.5.0rc1).
#
# Solution: Temporarily append ".9991" to stable versions (e.g., "3.5.0" -> "3.5.0.9991")
# so they sort after pre-releases, then reverse sort, then remove the suffix.
# This results in: 3.5.0, 3.5.0rc1, 3.5.0beta1, 3.5.0alpha1 (newest stable first).
version_reverse_sort() {
    sed -r "s/([0-9]+\.[0-9]+\.[0-9]+$)/\1\.9991/" | sort -Vr | sed s/\.9991$//
}

# Fetch all PostGIS release tags from GitHub API.
# Populates global: postgis_all_v3_versions (space-separated list of tags)
fetch_postgis_versions() {
    local github_repo="postgis/postgis"
    local tags_per_page=100
    local current_page=1
    postgis_all_v3_versions=""

    while true; do
        local api_response
        api_response="$(curl --fail --show-error --silent "https://api.github.com/repos/${github_repo}/tags?per_page=${tags_per_page}&page=${current_page}")" || {
            log_warn "Failed to fetch postgis tags from api.github.com"
            return 1
        }

        if echo "$api_response" | grep -q "API rate limit exceeded"; then
            die "API rate limit exceeded: $api_response"
        fi

        local fetched_tags tag_count
        fetched_tags=$(echo "$api_response" | jq -r '.[].name' 2>/dev/null || true)
        tag_count=$(echo "$fetched_tags" | sed '/^$/d' | wc -l)
        if ((tag_count == 0)); then
            break
        fi

        if ((current_page > MAX_GITHUB_API_PAGES)); then
            die "Too many pages (${current_page}) while fetching PostGIS tags - possible infinite loop"
        fi

        postgis_all_v3_versions+=" $fetched_tags"
        ((current_page++))
    done
}

# ---------------------------------------------------------------------------
# Version resolution and recording
# ---------------------------------------------------------------------------

# Resolve PostGIS package version from Debian apt repository.
#
# Arguments:
#   $1 - postgres_main: PostgreSQL major version (e.g., "17")
#   $2 - postgis_version: Requested PostGIS version (e.g., "3.5" or "master")
#   $3 - version_list: Debian Packages file content
#   $4 - version_dir: Version directory name (e.g., "17-3.5")
#   $5 - suite: Debian suite name (e.g., "bullseye")
#
# Sets globals (output):
#   postgisMajMin    - PostGIS major.minor (e.g., "3.5")
#   postgisPackageName   - Debian package name (e.g., "postgresql-17-postgis-3")
#   postgisFullVersion   - Full version from apt (e.g., "3.5.0+dfsg-1.pgdg...")
#   postgisMajor          - PostGIS major version for package suffix (e.g., "3")
#   postgisDocSrc     - Version string for documentation (e.g., "3.5.0")
#
# Sets globals (status):
#   debian_resolve_status  - "OK" or "SKIP"
#   debian_resolve_reason  - Reason if SKIP (e.g., "Debian package not available")
#   debian_resolve_requested - Requested major.minor
#   debian_resolve_found   - Found major.minor (may differ)
#   debian_resolve_found_ver - Full version found in apt
resolve_debian_postgis_version() {
    local postgres_main="$1"
    local postgis_version="$2"
    local version_list="$3"
    local version_dir="$4"
    local suite="$5"

    # Initialize output globals
    postgisPackageName=""
    postgisFullVersion=""
    postgisMajor=""
    postgisDocSrc=""
    postgisMajMin=""

    # Initialize status globals
    debian_resolve_requested=""
    debian_resolve_found=""
    debian_resolve_found_ver=""
    debian_resolve_reason=""
    debian_resolve_status="OK"

    # Master branch is built from source, not from Debian packages
    if [[ "$postgis_version" == "master" ]]; then
        postgisFullVersion="$postgis_version"
        postgisDocSrc="development: postgis, geos, proj, gdal"
        debian_resolve_status="OK"
        return 0
    fi

    # Extract major.minor from version (e.g., "3.5" from "3.5" or "3.5.0")
    local major minor
    major="$(echo "${postgis_version}" | cut -d. -f1)"
    minor="$(echo "${postgis_version}" | cut -d. -f2)"
    postgisMajMin="${major}.${minor}"
    debian_resolve_requested="$postgisMajMin"

    # Construct Debian package name and look up version in apt repository
    postgisPackageName="postgresql-${postgres_main}-postgis-${postgisMajMin%%.*}"
    debian_resolve_found_ver="$(echo "$version_list" | awk -F ': ' '$1 == "Package" { pkg = $2 } $1 == "Version" && pkg == "'"$postgisPackageName"'" { print $2; exit }' || true)"
    postgisFullVersion="$debian_resolve_found_ver"

    if [[ -z "$postgisFullVersion" ]]; then
        debian_resolve_status="SKIP"
        debian_resolve_reason="Debian package not available"
        return 0
    fi

    # Verify the found package matches our requested major.minor
    # (apt might have a different version than what we're looking for)
    local found_major found_minor found_major_minor
    found_major="$(echo "${postgisFullVersion}" | cut -d. -f1)"
    found_minor="$(echo "${postgisFullVersion}" | cut -d. -f2)"
    found_major_minor="${found_major}.${found_minor}"
    debian_resolve_found="$found_major_minor"

    if [[ "$found_major_minor" == "$postgisMajMin" ]]; then
        postgisMajor="${postgisMajMin%%.*}"
        # Strip Debian-specific suffix (e.g., "+dfsg-1.pgdg...") for documentation
        postgisDocSrc="${postgisFullVersion%%+*}"
    else
        debian_resolve_status="SKIP"
        debian_resolve_reason="PostGIS major.minor mismatch"
        postgisFullVersion=""
        postgisMajor=""
        postgisDocSrc=""
    fi
}

# Select the best PostGIS source version for Alpine builds.
#
# Strategy:
# 1. Prefer the latest stable version (no alpha/beta/rc) for the same major.minor series
# 2. If no stable exists and requested version is a pre-release, use that pre-release
# 3. Otherwise fall back to the latest available tag for the series (including pre-releases)
#
# Arguments:
#   $1 - major_minor: PostGIS major.minor (e.g., "3.6")
#   $2 - requested_version: Version from directory name (e.g., "3.6" or "3.6.0beta1")
#   $3 - available_versions: Space-separated list of all available tags
#
# Output: Selected version string (e.g., "3.6.0" or "3.6.0beta1")
select_postgis_src_version_for_alpine() {
    local major_minor="$1"
    local requested_version="$2"
    local available_versions="$3"

    local major minor
    major="${major_minor%%.*}"
    minor="${major_minor#*.}"

    # First, try to find a stable release (no letters = no alpha/beta/rc suffix)
    local stable_version
    stable_version="$(
        tr ' ' '\n' <<< "$available_versions" \
            | grep "^${major}\\.${minor}\\." \
            | grep -v '[a-zA-Z]' \
            | head -n 1 \
            || true
    )"
    if [[ -n "$stable_version" ]]; then
        echo "$stable_version"
        return 0
    fi

    # No stable release found - check if requested is a pre-release
    if [[ "$requested_version" =~ alpha|beta|rc ]]; then
        echo "$requested_version"
    else
        # Fall back to latest available (may be pre-release)
        tr ' ' '\n' <<< "$available_versions" \
            | grep "^${major}\\.${minor}\\." \
            | head -n 1 \
            || true
    fi
}

# Resolve PostGIS source version and SHA256 for Alpine builds.
# Alpine builds PostGIS from source, so we need to determine the exact
# source tag and download/verify the tarball.
#
# Arguments:
#   $1 - version_dir: Version directory name (e.g., "17-3.5")
#   $2 - postgis_version: PostGIS version from directory (e.g., "3.5" or "master")
#
# Requires globals:
#   postgisMajMin - Set by resolve_debian_postgis_version()
#   postgisFullVersion - Set by resolve_debian_postgis_version()
#   postgis_all_v3_versions_array_string - Set by fetch_remote_state()
#
# Sets globals:
#   srcVersion - PostGIS source tag (e.g., "3.5.0")
#   srcSha256  - SHA256 of source tarball
#   postgisDocSrc    - Updated to match Alpine source version
resolve_alpine_postgis_version() {
    local version_dir="$1"
    local postgis_version="$2"

    srcVersion=""
    srcSha256=""

    # Master branch doesn't need source resolution (built from git HEAD)
    if [[ "$postgis_version" == "master" ]]; then
        return 0
    fi

    if [[ -d "$version_dir/alpine" ]]; then
        srcVersion="$(select_postgis_src_version_for_alpine "$postgisMajMin" "$postgis_version" "$postgis_all_v3_versions_array_string")"
        if [[ -z "$srcVersion" ]]; then
            die "Unable to resolve PostGIS source version for alpine (postgisMajMin=$postgisMajMin, requested=$postgis_version)"
        fi
    else
        # Use Debian's resolved version, stripped of Debian-specific suffix
        srcVersion="${postgisFullVersion%%+*}"
    fi

    # Check cache first to avoid re-downloading same tarball
    if [[ -n "${postgis_tarball_sha256_cache[$srcVersion]:-}" ]]; then
        srcSha256="${postgis_tarball_sha256_cache[$srcVersion]}"
    else
        local tarball_url="https://github.com/postgis/postgis/archive/${srcVersion}.tar.gz"
        if ! srcSha256="$(curl -fsSL "$tarball_url" | sha256sum | awk '{ print $1 }')"; then
            die "Failed to download PostGIS tarball: $tarball_url"
        fi
        postgis_tarball_sha256_cache["$srcVersion"]="$srcSha256"
    fi
    postgisDocSrc="$srcVersion"
}

record_target() {
    local version_dir="$1"
    local postgres_display="$2"
    local postgres_main="$3"
    local postgis_version="$4"
    local variant="$5"      # default|alpine
    local os_doc="$6"       # e.g. debian:bullseye
    local os_label="$7"     # e.g. bullseye or alpine3.22
    local doc_src="$8"      # PostGIS column + patch for tag gen

    local bucket image_tag dockerfile_path
    if [[ "$variant" == "alpine" ]]; then
        bucket="$(detect_optimized_bucket "$version_dir" "alpine")"
        image_tag="${version_dir}-alpine"
        dockerfile_path="${version_dir}/alpine/Dockerfile"
    else
        bucket="$(detect_optimized_bucket "$version_dir" "default")"
        image_tag="${version_dir}"
        dockerfile_path="${version_dir}/Dockerfile"
        variant="default"
    fi

    echo "| [postgis/postgis:${image_tag}](${DOCKERHUB_TAGS_URL_BASE}${image_tag}) | [Dockerfile](${GITHUB_REPO_BLOB_BASE}/${dockerfile_path}) | ${os_doc} | ${postgres_display} | ${doc_src} |" >> "_dockerlists_${bucket}.md"

    local tags
    tags="$(build_tags "${postgres_main}" "${postgis_version}" "${variant}" "${os_label}" "${doc_src}")"
    echo "  - { postgres: '${postgres_main}', postgis: '${postgis_version}', variant: '${variant}', tags: '${tags}' }" >> "_matrixlist_${bucket}.yml"
    echo "$tags"
}

# ---------------------------------------------------------------------------
# Generation phases
# ---------------------------------------------------------------------------

init_outputs() {
    for optimized in "${OPTIMIZED_BUCKETS[@]}"; do
        rm -f "_dockerlists_${optimized}.md"
        {
            echo "<!-- This part is automatically generated by ./update.sh. Do not modify this section manually. -->"
            echo "| DockerHub image | Dockerfile | OS | Postgres | PostGIS |"
            echo "| --------------- | ---------- | -- | -------- | ------- |"
        } > "_dockerlists_${optimized}.md"

        rm -f "_matrixlist_${optimized}.yml"
        {
            echo "# This file is automatically generated by ./update.sh"
            echo "# Category: ${optimized}"
            echo "# Entries that successfully generated Dockerfiles"
            echo ""
        } > "_matrixlist_${optimized}.yml"
    done
}

fetch_git_hash() {
    local url="$1"
    local ref="$2"
    local name="$3"
    local hash

    if ! hash="$(git ls-remote "$url" "$ref" 2>/dev/null | awk '{ print $1; exit }')"; then
        log_warn "Failed to fetch $name git hash from $url"
        echo ""
        return 0
    fi

    if [[ -z "$hash" ]]; then
        log_warn "Empty $name git hash (ref: $ref) from $url"
        echo ""
        return 0
    fi

    log_info "$name git hash: ${hash:0:12}..."
    echo "$hash"
}

fetch_remote_state() {
    log_info "Fetching remote git hashes..."
    local -a repos=(
        "cgalGitHash|https://github.com/CGAL/cgal.git|heads/main|CGAL"
        "sfcgalGitHash|https://gitlab.com/SFCGAL/SFCGAL.git|heads/master|SFCGAL"
        "projGitHash|https://github.com/OSGeo/PROJ.git|heads/master|PROJ"
        "gdalGitHash|https://github.com/OSGeo/gdal.git|refs/heads/master|GDAL"
        "geosGitHash|https://github.com/libgeos/geos.git|heads/main|GEOS"
        "postgisGitHash|https://github.com/postgis/postgis.git|heads/master|PostGIS"
    )
    local entry var url ref name hash
    for entry in "${repos[@]}"; do
        IFS='|' read -r var url ref name <<< "$entry"
        hash="$(fetch_git_hash "$url" "$ref" "$name")"
        printf -v "$var" '%s' "$hash"
    done

    fetch_postgis_versions || die "Error fetching PostGIS versions"
    postgis_all_v3_versions="$(echo "$postgis_all_v3_versions" | sed '/^$/d' | grep '^3\.' | version_reverse_sort)"
    postgis_all_v3_versions_array_string="$(echo "$postgis_all_v3_versions" | tr '\n' ' ')"
    log_info "postgis_all_v3_versions_array_string = ${postgis_all_v3_versions_array_string}"
}

declare -a matrix_skip_comments=()
declare -A suitePackageList=()

# Populated in fetch_remote_state().
cgalGitHash=""
sfcgalGitHash=""
projGitHash=""
gdalGitHash=""
geosGitHash=""
postgisGitHash=""

# Mutable in-process cache to avoid re-downloading the same PostGIS tarball
# multiple times when several targets resolve to the same PostGIS source tag.
declare -A postgis_tarball_sha256_cache=()

# Generate Debian Dockerfile for a PostgreSQL/PostGIS version combination.
#
# Arguments:
#   $1 - version_dir: Version directory (e.g., "17-3.5")
#   $2 - postgres_version: PostgreSQL version string (e.g., "17")
#   $3 - postgres_main: PostgreSQL major version (e.g., "17")
#   $4 - postgis_version: PostGIS version (e.g., "3.5" or "master")
#   $5 - debian_suite: Debian suite name (e.g., "bullseye")
#   $6 - boost_version: Boost library version for SFCGAL (e.g., "1.74.0")
#
# Requires globals: postgisFullVersion, postgisMajor, postgisMajMin,
#                   postgisDocSrc (set by resolve_debian_postgis_version)
#
# Output: Generated Docker tags (space-separated)
generate_debian() {
    local version_dir="$1"
    local postgres_version="$2"
    local postgres_main="$3"
    local postgis_version="$4"
    local debian_suite="$5"
    local boost_version="$6"

    # If no Debian package available, create placeholder Dockerfile
    if [[ -z "$postgisFullVersion" ]]; then
        echo " # placeholder Dockerfile"                                            > "$version_dir/Dockerfile"
        echo " # Debian version of postgis $postgisFullVersion is not detected!" >> "$version_dir/Dockerfile"
        echo " # This is an autogenerated message of ./update.sh "                 >> "$version_dir/Dockerfile"
        rm -f "$version_dir/"*.sh "$version_dir/"*.md
        matrix_skip_comments+=("postgres: ${postgres_main}, postgis: ${postgis_version}, variant: default - Reason: placeholder (Debian ${debian_suite} package not available)")

        # Fall back to latest known version for documentation purposes
        local postgis_minor
        postgis_minor="$(echo "$postgisMajMin" | cut -d. -f2)"
        # Try stable version first, then any version including pre-releases
        postgisFullVersion="$(echo "$postgis_all_v3_versions" | grep "^3\.${postgis_minor}\." | grep -v '[a-zA-Z]' | version_reverse_sort | head -n 1 || true)"
        if [[ -z "${postgisFullVersion}" ]]; then
            postgisFullVersion="$(echo "$postgis_all_v3_versions" | grep "^3\.${postgis_minor}\." | version_reverse_sort | head -n 1 || true)"
        fi
        postgisDocSrc="$postgisFullVersion"
        return 0
    fi

    cp -p initdb-postgis.sh update-postgis.sh "$version_dir/"

    # Select appropriate template based on build type
    local template_file
    if [[ "$postgis_version" == "master" ]]; then
        template_file="Dockerfile.master.template"
    else
        template_file="Dockerfile.template"
    fi

    render_template "$template_file" "$version_dir/Dockerfile" \
        "%%TXT_AUTOGENERATED%%=$AUTOGENERATED_NOTICE" \
        "%%PG_MAJOR%%=$postgres_version" \
        "%%POSTGIS_MAJOR%%=$postgisMajor" \
        "%%POSTGIS_VERSION%%=$postgisFullVersion" \
        "%%POSTGIS_GIT_HASH%%=$postgisGitHash" \
        "%%CGAL_GIT_HASH%%=$cgalGitHash" \
        "%%SFCGAL_GIT_HASH%%=$sfcgalGitHash" \
        "%%PROJ_GIT_HASH%%=$projGitHash" \
        "%%GDAL_GIT_HASH%%=$gdalGitHash" \
        "%%GEOS_GIT_HASH%%=$geosGitHash" \
        "%%BOOST_VERSION%%=$boost_version" \
        "%%DEBIAN_VERSION%%=$debian_suite"

    local tags
    tags="$(record_target "$version_dir" "$postgres_version" "$postgres_main" "$postgis_version" "default" "debian:${debian_suite}" "${debian_suite}" "$postgisDocSrc")"
    echo "$tags"
}

# Generate Alpine Dockerfile for a PostgreSQL/PostGIS version combination.
# Alpine builds PostGIS from source rather than using packages.
#
# Arguments:
#   $1 - version_dir: Version directory (e.g., "17-3.5")
#   $2 - postgres_version: PostgreSQL version string (e.g., "17")
#   $3 - postgres_main: PostgreSQL major version (e.g., "17")
#   $4 - postgis_version: PostGIS version (e.g., "3.5")
#
# Requires globals: srcVersion, srcSha256, postgisDocSrc
#                   (set by resolve_alpine_postgis_version)
#
# Output: Generated Docker tags (space-separated), empty if no Alpine variant
generate_alpine() {
    local version_dir="$1"
    local postgres_version="$2"
    local postgres_main="$3"
    local postgis_version="$4"

    local variant="alpine"
    if [[ ! -d "$version_dir/$variant" ]]; then
        return 0
    fi

    cp -p initdb-postgis.sh update-postgis.sh "$version_dir/$variant/"

    render_template "Dockerfile.alpine.template" "$version_dir/$variant/Dockerfile" \
        "%%TXT_AUTOGENERATED%%=$AUTOGENERATED_NOTICE" \
        "%%PG_MAJOR%%=$postgres_version" \
        "%%POSTGIS_VERSION%%=$srcVersion" \
        "%%POSTGIS_SHA256%%=$srcSha256"

    local tags
    tags="$(record_target "$version_dir" "$postgres_version" "$postgres_main" "$postgis_version" "alpine" "alpine:${DEFAULT_ALPINE_SUITE}" "alpine${DEFAULT_ALPINE_SUITE}" "$postgisDocSrc")"
    echo "$tags"
}

# Fetch and cache Debian package list for a suite.
# Uses global cache to avoid redundant downloads.
#
# Arguments:
#   $1 - suite: Debian suite name (e.g., "bullseye")
#
# Sets global: suitePackageList[$suite]
fetch_suite_package_list() {
    local suite="$1"
    if [[ -z "${suitePackageList["$suite"]:+isset}" ]]; then
        suitePackageList["$suite"]="$(curl -fsSL "${PACKAGES_BASE}/${suite}-pgdg/main/binary-amd64/Packages.bz2" | bunzip2)"
    fi
}

# Process a single version directory, generating Dockerfiles for all variants.
#
# Arguments:
#   $1 - version_dir: Version directory name (e.g., "17-3.5")
#
# This is the main entry point for processing each PostgreSQL/PostGIS combination.
# It coordinates Debian and Alpine variant generation.
process_version() {
    local version_dir="$1"

    # Parse version directory name into PostgreSQL and PostGIS versions
    local postgres_version postgis_version
    IFS=- read -r postgres_version postgis_version <<< "$version_dir"

    log_info "===== Generate ${version_dir} ====="

    # Determine Debian suite and fetch package list
    local suite_tag debian_suite
    suite_tag="${DEBIAN_SUITE[$postgres_version]:-$DEFAULT_DEBIAN_SUITE}"
    debian_suite="${suite_tag%%-slim}"

    fetch_suite_package_list "$debian_suite"

    # Extract main PostgreSQL version (strip pre-release suffix like alpha/beta/rc)
    local postgres_main
    postgres_main="$(echo "$postgres_version" | awk -F 'alpha|beta|rc' '{print $1}')"

    # Fetch combined package list (main + version-specific)
    local package_list
    package_list="$(echo "${suitePackageList["$debian_suite"]}"; curl -fsSL "${PACKAGES_BASE}/${debian_suite}-pgdg/${postgres_main}/binary-amd64/Packages.bz2" | bunzip2)"

    # Get Boost version for SFCGAL (varies by Debian release)
    local boost_version
    case "$debian_suite" in
        bullseye) boost_version="1.74.0" ;;
        trixie)   boost_version="1.88.0" ;;
        *) die "Unknown debian suite: ${debian_suite}" ;;
    esac

    # Resolve PostGIS package version from Debian repository
    resolve_debian_postgis_version "$postgres_main" "$postgis_version" "$package_list" "$version_dir" "$debian_suite"

    # --- Generate Debian variant ---
    local debian_tags=""
    if [[ "$postgis_version" == "master" ]]; then
        debian_tags="$(generate_debian "$version_dir" "$postgres_version" "$postgres_main" "$postgis_version" "$debian_suite" "$boost_version" || true)"
        log_info "${version_dir} debian | OK suite=${suite_tag} postgis=master tags=\"${debian_tags}\""
    elif [[ "${debian_resolve_status}" == "SKIP" ]]; then
        generate_debian "$version_dir" "$postgres_version" "$postgres_main" "$postgis_version" "$debian_suite" "$boost_version" >/dev/null || true
        if [[ "${debian_resolve_reason}" == "PostGIS major.minor mismatch" ]]; then
            log_warn "${version_dir} debian | SKIP pkg=${postgisPackageName} reason=\"${debian_resolve_reason}\" requested=${debian_resolve_requested} found=${debian_resolve_found}"
        else
            log_warn "${version_dir} debian | SKIP pkg=${postgisPackageName} reason=\"${debian_resolve_reason}\" requested=${debian_resolve_requested}"
        fi
    else
        debian_tags="$(generate_debian "$version_dir" "$postgres_version" "$postgres_main" "$postgis_version" "$debian_suite" "$boost_version" || true)"
        log_info "${version_dir} debian | OK pkg=${postgisPackageName} ver=${postgisFullVersion} tags=\"${debian_tags}\""
    fi

    # --- Generate Alpine variant (if exists) ---
    if [[ -d "$version_dir/alpine" ]]; then
        resolve_alpine_postgis_version "$version_dir" "$postgis_version"
        local alpine_tags
        alpine_tags="$(generate_alpine "$version_dir" "$postgres_version" "$postgres_main" "$postgis_version" || true)"
        log_info "${version_dir} alpine | OK src=${srcVersion} tags=\"${alpine_tags}\""
    fi
}

generate_matrix_yml() {
    local output_file="$1"
    local temp_file
    temp_file="$(mktemp)" || die "Failed to create temporary file"
    trap 'rm -f "$temp_file"' RETURN

    cat > "$temp_file" << EOF
# =============================================================================
# WARNING: AUTOMATICALLY GENERATED by ./update.sh - DO NOT EDIT MANUALLY!
# Used by: .github/workflows/*.yml
# =============================================================================
# - build_targets: All buildable postgres-postgis-variant combinations
# =============================================================================

EOF

    if [ ${#matrix_skip_comments[@]} -gt 0 ]; then
        echo "# --- Placeholder/skipped combinations (NOT included in build target list) ---" >> "$temp_file"
        for comment in "${matrix_skip_comments[@]}"; do
            echo "# - ${comment}" >> "$temp_file"
        done
        echo "" >> "$temp_file"
    fi

    echo "build_targets:" >> "$temp_file"

    local has_entries=false
    for optimized in "${OPTIMIZED_BUCKETS[@]}"; do
        if [ -f "_matrixlist_${optimized}.yml" ]; then
            grep "^  -" "_matrixlist_${optimized}.yml" >> "$temp_file" 2>/dev/null && has_entries=true
        fi
    done

    if [ "$has_entries" = false ]; then
        echo "  []" >> "$temp_file"
    fi

    local target_count
    target_count=$(grep -c "^  - { postgres:" "$temp_file" || echo "0")
    {
        echo ""
        echo ""
        echo "# =============================================================================="
        echo "# Summary: ${target_count} combinations"
        echo "# =============================================================================="
        echo "# End of matrix.yml"
    } >> "$temp_file"

    if [ -f "$output_file" ] && cmp -s "$temp_file" "$output_file"; then
        log_info "matrix.yml unchanged"
        rm -f "$temp_file"
    else
        mv "$temp_file" "$output_file"
        chmod 644 "$output_file"
        log_info "matrix.yml generated/updated"
    fi
    trap - RETURN
}

main() {
    check_bash_version

    # Parse options
    local -a args=()
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h|--help)
                usage
                exit 0
                ;;
            --)
                shift
                args+=("$@")
                break
                ;;
            -*)
                die "Unknown option: $1. Use --help for usage information." 2
                ;;
            *)
                args+=("$1")
                shift
                ;;
        esac
    done

    # Check required dependencies
    local -a deps=(curl jq git bunzip2 sha256sum)
    local dep
    for dep in "${deps[@]}"; do
        require_cmd "$dep"
    done

    local versions=( "${args[@]}" )
    local update_all=false

    if [ ${#versions[@]} -eq 0 ]; then
        update_all=true
        shopt -s nullglob
        versions=( [0-9]*/Dockerfile )
        shopt -u nullglob
    fi
    versions=( "${versions[@]%/Dockerfile}" )

    mapfile -t versions < <(printf '%s\n' "${versions[@]}" | sort -V)

    if [[ "$update_all" == true ]]; then
        init_outputs
    else
        log_info "Specific version(s) requested: ${versions[*]}"
        log_info "Skipping global metadata updates (README.md, matrix.yml)"
    fi

    fetch_remote_state

    for version_dir in "${versions[@]}"; do
        process_version "$version_dir"
    done

    if [[ "$update_all" == true ]]; then
        log_info "|-------------------------------|"
        log_info "|-   Generated README tables   -|"
        log_info "|-------------------------------|"
        for optimized in "${OPTIMIZED_BUCKETS[@]}"; do
            log_info "---- ${optimized} [ _dockerlists_${optimized}.md ] ----"
            cat "_dockerlists_${optimized}.md"
            echo " "
        done

        log_info "Applying README updates"
        bash ./apply-readme.sh

        log_info "Generating matrix.yml from _matrixlist_*.yml files"
        generate_matrix_yml "$MATRIX_FILE"
    fi

    log_info "update done && git status:"
    git status
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    main "$@"
fi
