name: "Localtest"
# testing the workflow
on:
    push:
    pull_request:
    schedule:
        - cron: '15 5 * * 1'

jobs:
  localtest:
    name: "testing ./localtest.sh ( update.sh and build test and push to local registry )"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker ps -a
      - name: Install manifest-tool
        run: |
              wget https://github.com/estesp/manifest-tool/releases/download/v2.0.8/binaries-manifest-tool-2.0.8.tar.gz
              mkdir manifest-tool
              tar -xvzf binaries-manifest-tool-2.0.8.tar.gz -C manifest-tool
              sudo mv manifest-tool/manifest-tool-linux-amd64 /usr/local/bin/manifest-tool
              manifest-tool -v
      - run: pip install lastversion
      - run: ./localtest.sh
      - run: docker images
