name: Docker PostGIS CI

# for building linux/amd64 ( x86-64 ) images !

on:
  push:
  pull_request:
  schedule:
    - cron: '15 5 * * 1'

defaults:
  run:
    shell: bash

jobs:

  make-docker-images:
    strategy:
      matrix:
        postgres: [11, 12, 13, 14, 15]
        postgis: ['3.3']
        variant: [default, alpine]
        include:
          - postgres: 10
            postgis: '3.2'
            variant: default
          - postgres: 10
            postgis: '3.2'
            variant: alpine

          - postgres: 14
            postgis: master
            variant: default
          - postgres: 15
            postgis: master
            variant: default

    name: Build docker image for ${{ matrix.postgres }}-${{ matrix.postgis }} variant ${{ matrix.variant }}
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.postgis == 'master' }}
    env:
      # Alpine image version
      ALPINE_VERSION: '3.16'
      # Workflow name for internal logic
      WORKFLOW: main
      # Docker image Repo and Image name
      REPO_NAME: postgis
      IMAGE_NAME: postgis
      # Docker image version and variant
      VERSION: ${{ matrix.postgres }}-${{ matrix.postgis }}
      VARIANT: ${{ matrix.variant }}
      # Docker image tag postfix!  in this case, no postfix!
      TAG_POSTFIX: ''

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: "debug: Inspect the base alpine image postgres:${{ matrix.postgres }}-alpine${{ env.ALPINE_VERSION }} "
      if: ${{ env.VARIANT == 'alpine' }}
      run: docker pull postgres:${{ matrix.postgres }}-alpine${{ env.ALPINE_VERSION }} && docker inspect postgres:${{ matrix.postgres }}-alpine${{ env.ALPINE_VERSION }}

    - name: Build docker image for ${{ env.VERSION }} ${{ env.VARIANT }}${{ env.TAG_POSTFIX }}
      run: make test

    - name: "debug: docker images"
      run: docker images

    - name: "debug: docker inspect ${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}${{ env.TAG_POSTFIX }}"
      if: ${{ env.VARIANT == 'default' }}
      run: docker inspect ${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}${{ env.TAG_POSTFIX }}

    - name: "debug: docker inspect ${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}-${{ env.VARIANT }}${{ env.TAG_POSTFIX }}"
      if: ${{ env.VARIANT == 'alpine' }}
      run: docker inspect ${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}-${{ env.VARIANT }}${{ env.TAG_POSTFIX }}

    - name: Login to dockerhub
      uses: docker/login-action@v1
      if: ${{  (github.ref == 'refs/heads/master') && (github.event_name != 'pull_request')  }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Push docker image to dockerhub
      if: ${{  (github.ref == 'refs/heads/master') && (github.event_name != 'pull_request')  }}
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      run: make push

