name: Docker PostGIS CI

on:
  push:
  pull_request:
  schedule:
    - cron: '15 5 * * 1'

defaults:
  run:
    shell: bash

jobs:

  make-docker-images:
    strategy:
      matrix:
        runner-platform: ['ubuntu-24.04', 'ubuntu-24.04-arm']
        postgres: [13, 14, 15, 16, 17 ]
        postgis: ['3.5']
        variant: [default, alpine]
        include:
          - postgres: 16
            postgis: master
            variant: default
            runner-platform: 'ubuntu-24.04'
          - postgres: 17
            postgis: master
            variant: default
            runner-platform: 'ubuntu-24.04'
          - postgres: 16
            postgis: master
            variant: default
            runner-platform: 'ubuntu-24.04-arm'
          - postgres: 17
            postgis: master
            variant: default
            runner-platform: 'ubuntu-24.04-arm'
          - postgres: 17
            postgis: '3.6'
            variant: alpine
            runner-platform: 'ubuntu-24.04'
          - postgres: 17
            postgis: '3.6'
            variant: alpine
            runner-platform: 'ubuntu-24.04-arm'
          - postgres: 18
            postgis: '3.6'
            variant: alpine
            runner-platform: 'ubuntu-24.04'
          - postgres: 18
            postgis: '3.6'
            variant: alpine
            runner-platform: 'ubuntu-24.04-arm'
          - postgres: 18
            postgis: '3.6'
            variant: default
            runner-platform: 'ubuntu-24.04'
          - postgres: 18
            postgis: '3.6'
            variant: default
            runner-platform: 'ubuntu-24.04-arm'

    name: ${{ matrix.postgres }}-${{ matrix.postgis }}-${{ matrix.variant }} ${{ matrix.runner-platform }} - Build Docker image
    runs-on: ${{ matrix.runner-platform }}
    continue-on-error: ${{ matrix.postgis == 'master' }}
    env:
      VERSION: ${{ matrix.postgres }}-${{ matrix.postgis }}
      VARIANT: ${{ matrix.variant }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Build docker image for ${{ env.VERSION }} ${{ env.VARIANT }}
      run: make test

    - name: Login to dockerhub
      uses: docker/login-action@v3
      if: ${{ (github.repository == 'postgis/docker-postgis') && (github.ref == 'refs/heads/master') && (github.event_name != 'pull_request') }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Push docker image to dockerhub
      # !!!! ONLY push the images when built on ubuntu-24.04 x86 runner for now, NOT for ubuntu-24.04-arm runners
      if: ${{ (github.repository == 'postgis/docker-postgis') && (github.ref == 'refs/heads/master') && (github.event_name != 'pull_request') && ( matrix.runner-platform == 'ubuntu-24.04' ) }}
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      run: make push

